name: bioinfo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - tqdm
  - pyyaml
  - scikit-learn
  - scikit-bio
  - jupyter
  - xgboost
  - pandas
  - scipy
  - seaborn
  - lightgbm
  - openpyxl
  - ipykernel
  - matplotlib
  - numpy
  - pip
  - pip:
    - shap
